# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build_Test_Publish
  jobs:
  - job: Build_Test_Publish
    steps:
    - task: NuGetToolInstaller@1
    
    - script: |
        cd Application
        dotnet restore
        dotnet build --configuration Release
        dotnet test aspnet-core-dotnet-core.UnitTests/aspnet-core-dotnet-core.UnitTests.csproj
        dotnet publish --configuration $(buildConfiguration) --output "$(build.artifactstagingdirectory)"
      displayName: 'dotnet build unit test and publish'

    - script: | 
        zip -qq -r Application.zip $(build.artifactstagingdirectory)
      displayName: Archive Application

        
    - task: CopyFiles@2
      displayName: 'Copy runsettings file'
      inputs:
        Contents: '**/*.runsettings'
        TargetFolder: '$(build.artifactstagingdirectory)/FunctionalTests'
        flattenFolders: true

    - task: CopyFiles@2
      displayName: 'Copy ARM templates'
      inputs:
        SourceFolder: ArmTemplates
        TargetFolder: '$(build.artifactstagingdirectory)/deployment'

    - publish: $(build.artifactstagingdirectory)
      displayName: 'Publish Artifact'
      artifact: adonetexample

    - script: |
        ls -la $(build.artifactstagingdirectory)
      displayName: 'List Artifactstagingdirectory Contents'

- stage: Deploy
  dependsOn: Build_Test_Publish
  jobs:
  - job: Deploy
    steps:
    - download: current
      artifact: adonetexample
      
    - script: |
        ls -la $(pipeline.workspace)/adonetexample

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'adonetexample - Azure'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az group create --name "adonetexample-rg" --location "eastus"
          az deployment group create --resource-group "adonetexample-rg" --template-file $(pipeline.workspace)/deployment/linux-webapp-template.json --parameters webAppName="adonetexample" hostingPlanName="adonetexample-plan" appInsightsLocation="eastus" sku="S1 Standard"
    
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'adonetexample - Azure'
        appType: 'webAppLinux'
        WebAppName: 'adonetexample'
        packageForLinux: '$(pipeline.workspace)/**/*.zip'
        RuntimeStack: 'DOTNETCORE|3.1'